### ISSUE TITLE
Как подключить данный модуль?

### ISSUE THREAD

**Issue by dark46** [hiqdev/yii2-merchant#1]
Можно пример?

**Comment by hiqsol** [comment]
Сейчас используется только в нашем большом проекте [hipanel](https://github.com/hiqdev/hipanel-core), в финансовом модуле, вот тут можно увидеть [конфиг](https://github.com/hiqdev/hipanel-module-finance/blob/master/src/config/hisite.php).

Сорри если не сильно помог, но если будут более конкретные вопросы - ответим.

**Comment by SilverFire** [comment]
@dark46, как уже сказал @hiqsol, если будут конкретны вопросы - ответим. Пока закрываю
